### ISSUE TITLE
Father-son relationship

### ISSUE THREAD

**Issue by edgonzalezj** [FlowingCode/OrgChartAddon#10]
Hi.

It would be very useful for us not only to have a father-son relationship but also a relationship between siblings. It could be possible? Do you have this in consideration?

Thank you!!!!

**Comment by mlopezFC** [comment]
Hi! ... can you detail your requirement a little bit more?
Two items that belong to the same parent are "siblings" so that kind of relationship is already supported.
Remember that if the base library (https://github.com/dabeng/OrgChart) does not support what you want, then maybe it's better to create an issue in their repository.
Regards.

**Comment by mlopezFC** [comment]
Closing this one given that there was not feedback for a while. Please reopen if you have more information.
