### ISSUE TITLE
Node Template

### ISSUE THREAD

**Issue by aorsorlu** [FlowingCode/OrgChartAddon#5]
Hello.
 
Would you please implement node template feature of OrgChart.
https://rawgit.com/dabeng/OrgChart/master/demo/custom-template.html

Thanks.

**Comment by javier-godoy** [comment]
Hi! I pushed a first approach in [branches/NodeTemplate](https://github.com/FlowingCode/OrgChartAddon/tree/NodeTemplate)

For ES6, you can use it as:
```
      chart.setNodeTemplate("return `<span>${item.name}</span>`;");
```

ES5, however, does not support backticks, so if you need to maintain IE11 compatibility, you have to rewrite it as:
```	  
      chart.setNodeTemplate("return '<span>'+item.name+'</span>';");
```

It would be better to have something simpler like ```chart.setNodeTemplate("<span>${item.name}</span>")``` but that would require some processing of the template in order to support both ES5 and ES6. What do you think?

**Comment by aorsorlu** [comment]
Hi! `chart.setNodeTemplate("<span>${item.name}</span>")` would be awesome, but if it means much work for you, `chart.setNodeTemplate("return '<span>'+item.name+'</span>';");` is also suitable. More browser support is better.

**Comment by javier-godoy** [comment]
The supported way to do it will be by specifying the function body in `setNodeTemplate` (that means that, if you need ES5 support, the function body must not use template literals).  However, there is an experimental  rewriter that will produce an ES5 concatenation from an ES6 template literal.
